version: "2"
services:
  mongo:
    container_name: expressbase-mongo-db
    image: mongo
    volumes: 
      - expressbase-volume
    ports:
      - "27017:27017"
    networks: 
      - expressbase-network
  redis:
    container_name: expressbase-redis-cache
    image: redis
    expose:
      - 6379
    networks: 
      - expressbase-network
  app: 
    container_name: expressbase-service
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    links: 
      - mongo
      - redis
    ports:
      - "8080:3000/tcp"
    networks: 
      - expressbase-network

networks: 
  expressbase-network:
    driver: bridge

volumes: 
  expressbase-volume: