postgres:
  image: postgres:latest
  ports:
    - '5432:5432'
  environment:
    POSTGRES_USER: 'ctbadmin'
    POSTGRES_PASSWORD: 'ctbpassword'
    POSTGRES_DB: 'ctbLocal'
  volumes:
    - ./init:/docker-entrypoint-initdb.d/