name: Test, build, deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    name: Run tests
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: npm install
      - name: Run jest unit tests
        run: npm test
      - name: Run JS linter
        run: npm run lint
      - name: Run Cypress end-to-end
        uses: cypress-io/github-action@v1
        with:
          # we have already installed all dependencies above
          install: false
          start: npm run start:cypress
      - name: Run quality analysis on SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_SONAR_TOKEN }}
  deploy:
    name: Build container and deploy
    env:
      AZURE_CONTAINER_REGISTRY_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY_SERVER }}
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build -t base --build-arg GITHUB_SHA_ARG=${{ github.sha }} .
      - name: Tag :latest
        run: docker tag base $AZURE_CONTAINER_REGISTRY_SERVER/cra-claim-tax-benefits:latest
      - name: Tag :$GITHUB_SHA
        run: docker tag base $AZURE_CONTAINER_REGISTRY_SERVER/cra-claim-tax-benefits:${{ github.sha }}
      - name: Login into Azure Container Registry
        env:
          AZURE_CONTAINER_REGISTRY_USERNAME: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          AZURE_CONTAINER_REGISTRY_PASSWORD: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
        run: docker login -u $AZURE_CONTAINER_REGISTRY_USERNAME -p $AZURE_CONTAINER_REGISTRY_PASSWORD $AZURE_CONTAINER_REGISTRY_SERVER
      - name: Push container to Azure Container Registry
        run: docker push $AZURE_CONTAINER_REGISTRY_SERVER/cra-claim-tax-benefits
      - name: Login to Azure
        uses: Azure/github-actions/login@d0e5a0afc6b9d8d19c9ade8e2446ef3c20e260d4
        env:
          AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
          AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
          AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}
      - name: Update container image in Azure App Service for Containers
        uses: Azure/github-actions/cli@843845a95833e81c790d80c6e2fa714ccbd5e145
        env:
          AZURE_SCRIPT: az webapp config container set --resource-group cdscracollab-innovation-rg
            --name claim-tax-benefits --docker-custom-image-name $AZURE_CONTAINER_REGISTRY_SERVER/cra-claim-tax-benefits:$GITHUB_SHA
